### ISSUE TITLE
Use systemd to install the script as a startup service

### ISSUE THREAD

**Issue by T-Grave** [GoXLR-on-Linux/goxlr-on-linux#2] opened 2021-03-27 11:47 UTC

**Comment by lm41** [comment] 2022-05-29 14:23
There is a systemd service that does the job on Manjaro. [goxlr-on-manjaro](https://github.com/FrostyCoolSlug/goxlr-on-manjaro) I haven't tried it on other distributions, but it seems to work as intended. 
For the long run we should look into working with the kernel patch. @FrostyCoolSlug I think we should close this issue and move the goxlr-on-manjaro repo to the org with a new name (maybe goxlr-with-systemd) even if I think that in the long run we should switch from the scripts to the kernel variant.

**Comment by FrostyCoolSlug** [comment] 2022-06-16 00:11
I don't think the goxlr-on-manjaro repo should be pulled into here, there are quite a few substantial issues with it's behaviour that are difficult to (and ultimately never) resolved. Now that the kernel patch is hitting mainline, and becoming present in general usage kernels, needing systemd to handle things has dropped significantly from a priority perspective, as 'out the box' behaviour is now generally normalised. So I suggest closing this on that basis.

**Closed** 2022-06-16 14:40 UTC
Labels: question
